[package]
name = "aml-token"
version.workspace = true
edition.workspace = true

[dependencies]
aml-core.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true